fruit='Mango! M Mango Hhh'
#strings are immutable
print(len(fruit))
print(fruit[0:-2])
print(fruit[:3])
print(fruit[-4:len(fruit)-1])
nm='minal'
print(nm[-4:-2])
print(fruit.upper())
print(fruit.lower())
print(fruit.rstrip("!"))
print(fruit.replace("man",'john'))
print(fruit.split(" "))
print(fruit.capitalize())
print(fruit.center(30))
print(fruit.count('mango'))
print(fruit.endswith("!!!"))
print(fruit.find("fgo"))
print(fruit.index('go'))
print(fruit.isalnum())
print(fruit.isalpha())
print(fruit.isprintable())
print(fruit.istitle())
print(fruit.swapcase())
print(fruit.title())